/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppBodegaIndexRouteImport } from './routes/_app.bodega.index'
import { Route as AppBodegaProveedoresInsumosRouteImport } from './routes/_app.bodega.proveedores-insumos'
import { Route as AppBodegaInventarioRouteImport } from './routes/_app.bodega.inventario'
import { Route as AppBodegaComprasRouteImport } from './routes/_app.bodega.compras'
import { Route as AppBodegaInventarioIdRouteImport } from './routes/_app.bodega.inventario.$id'
import { Route as AppBodegaComprasNuevaRouteImport } from './routes/_app.bodega.compras.nueva'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppBodegaIndexRoute = AppBodegaIndexRouteImport.update({
  id: '/_app/bodega/',
  path: '/bodega/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppBodegaProveedoresInsumosRoute =
  AppBodegaProveedoresInsumosRouteImport.update({
    id: '/_app/bodega/proveedores-insumos',
    path: '/bodega/proveedores-insumos',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppBodegaInventarioRoute = AppBodegaInventarioRouteImport.update({
  id: '/_app/bodega/inventario',
  path: '/bodega/inventario',
  getParentRoute: () => rootRouteImport,
} as any)
const AppBodegaComprasRoute = AppBodegaComprasRouteImport.update({
  id: '/_app/bodega/compras',
  path: '/bodega/compras',
  getParentRoute: () => rootRouteImport,
} as any)
const AppBodegaInventarioIdRoute = AppBodegaInventarioIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppBodegaInventarioRoute,
} as any)
const AppBodegaComprasNuevaRoute = AppBodegaComprasNuevaRouteImport.update({
  id: '/nueva',
  path: '/nueva',
  getParentRoute: () => AppBodegaComprasRoute,
} as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/bodega/compras': typeof AppBodegaComprasRouteWithChildren
  '/bodega/inventario': typeof AppBodegaInventarioRouteWithChildren
  '/bodega/proveedores-insumos': typeof AppBodegaProveedoresInsumosRoute
  '/bodega/': typeof AppBodegaIndexRoute
  '/bodega/compras/nueva': typeof AppBodegaComprasNuevaRoute
  '/bodega/inventario/$id': typeof AppBodegaInventarioIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/bodega/compras': typeof AppBodegaComprasRouteWithChildren
  '/bodega/inventario': typeof AppBodegaInventarioRouteWithChildren
  '/bodega/proveedores-insumos': typeof AppBodegaProveedoresInsumosRoute
  '/bodega': typeof AppBodegaIndexRoute
  '/bodega/compras/nueva': typeof AppBodegaComprasNuevaRoute
  '/bodega/inventario/$id': typeof AppBodegaInventarioIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_app/bodega/compras': typeof AppBodegaComprasRouteWithChildren
  '/_app/bodega/inventario': typeof AppBodegaInventarioRouteWithChildren
  '/_app/bodega/proveedores-insumos': typeof AppBodegaProveedoresInsumosRoute
  '/_app/bodega/': typeof AppBodegaIndexRoute
  '/_app/bodega/compras/nueva': typeof AppBodegaComprasNuevaRoute
  '/_app/bodega/inventario/$id': typeof AppBodegaInventarioIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/register'
    | '/bodega/compras'
    | '/bodega/inventario'
    | '/bodega/proveedores-insumos'
    | '/bodega/'
    | '/bodega/compras/nueva'
    | '/bodega/inventario/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/register'
    | '/bodega/compras'
    | '/bodega/inventario'
    | '/bodega/proveedores-insumos'
    | '/bodega'
    | '/bodega/compras/nueva'
    | '/bodega/inventario/$id'
  id:
    | '__root__'
    | '/login'
    | '/register'
    | '/_app/bodega/compras'
    | '/_app/bodega/inventario'
    | '/_app/bodega/proveedores-insumos'
    | '/_app/bodega/'
    | '/_app/bodega/compras/nueva'
    | '/_app/bodega/inventario/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  AppBodegaComprasRoute: typeof AppBodegaComprasRouteWithChildren
  AppBodegaInventarioRoute: typeof AppBodegaInventarioRouteWithChildren
  AppBodegaProveedoresInsumosRoute: typeof AppBodegaProveedoresInsumosRoute
  AppBodegaIndexRoute: typeof AppBodegaIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/bodega/': {
      id: '/_app/bodega/'
      path: '/bodega'
      fullPath: '/bodega/'
      preLoaderRoute: typeof AppBodegaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/bodega/proveedores-insumos': {
      id: '/_app/bodega/proveedores-insumos'
      path: '/bodega/proveedores-insumos'
      fullPath: '/bodega/proveedores-insumos'
      preLoaderRoute: typeof AppBodegaProveedoresInsumosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/bodega/inventario': {
      id: '/_app/bodega/inventario'
      path: '/bodega/inventario'
      fullPath: '/bodega/inventario'
      preLoaderRoute: typeof AppBodegaInventarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/bodega/compras': {
      id: '/_app/bodega/compras'
      path: '/bodega/compras'
      fullPath: '/bodega/compras'
      preLoaderRoute: typeof AppBodegaComprasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/bodega/inventario/$id': {
      id: '/_app/bodega/inventario/$id'
      path: '/$id'
      fullPath: '/bodega/inventario/$id'
      preLoaderRoute: typeof AppBodegaInventarioIdRouteImport
      parentRoute: typeof AppBodegaInventarioRoute
    }
    '/_app/bodega/compras/nueva': {
      id: '/_app/bodega/compras/nueva'
      path: '/nueva'
      fullPath: '/bodega/compras/nueva'
      preLoaderRoute: typeof AppBodegaComprasNuevaRouteImport
      parentRoute: typeof AppBodegaComprasRoute
    }
  }
}

interface AppBodegaComprasRouteChildren {
  AppBodegaComprasNuevaRoute: typeof AppBodegaComprasNuevaRoute
}

const AppBodegaComprasRouteChildren: AppBodegaComprasRouteChildren = {
  AppBodegaComprasNuevaRoute: AppBodegaComprasNuevaRoute,
}

const AppBodegaComprasRouteWithChildren =
  AppBodegaComprasRoute._addFileChildren(AppBodegaComprasRouteChildren)

interface AppBodegaInventarioRouteChildren {
  AppBodegaInventarioIdRoute: typeof AppBodegaInventarioIdRoute
}

const AppBodegaInventarioRouteChildren: AppBodegaInventarioRouteChildren = {
  AppBodegaInventarioIdRoute: AppBodegaInventarioIdRoute,
}

const AppBodegaInventarioRouteWithChildren =
  AppBodegaInventarioRoute._addFileChildren(AppBodegaInventarioRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  AppBodegaComprasRoute: AppBodegaComprasRouteWithChildren,
  AppBodegaInventarioRoute: AppBodegaInventarioRouteWithChildren,
  AppBodegaProveedoresInsumosRoute: AppBodegaProveedoresInsumosRoute,
  AppBodegaIndexRoute: AppBodegaIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
