/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CartaIdMesaRouteImport } from './routes/carta.$idMesa'
import { Route as AppMenuRouteImport } from './routes/_app.menu'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppConfiguracionRouteImport } from './routes/_app.configuracion'
import { Route as AppBodegaRouteImport } from './routes/_app.bodega'
import { Route as AppMenuIndexRouteImport } from './routes/_app.menu.index'
import { Route as AppConfiguracionIndexRouteImport } from './routes/_app.configuracion.index'
import { Route as AppBodegaIndexRouteImport } from './routes/_app.bodega.index'
import { Route as AppMenuRecetasRouteImport } from './routes/_app.menu.recetas'
import { Route as AppMenuProductosRouteImport } from './routes/_app.menu.productos'
import { Route as AppMenuCategoriasRouteImport } from './routes/_app.menu.categorias'
import { Route as AppConfiguracionUsuariosRouteImport } from './routes/_app.configuracion.usuarios'
import { Route as AppConfiguracionMesasRouteImport } from './routes/_app.configuracion.mesas'
import { Route as AppBodegaProveedoresInsumosRouteImport } from './routes/_app.bodega.proveedores-insumos'
import { Route as AppBodegaInventarioRouteImport } from './routes/_app.bodega.inventario'
import { Route as AppBodegaComprasRouteImport } from './routes/_app.bodega.compras'
import { Route as AppMenuRecetasIndexRouteImport } from './routes/_app.menu.recetas.index'
import { Route as AppBodegaInventarioIndexRouteImport } from './routes/_app.bodega.inventario.index'
import { Route as AppMenuRecetasNuevaRouteImport } from './routes/_app.menu.recetas.nueva'
import { Route as AppMenuRecetasIdRouteImport } from './routes/_app.menu.recetas.$id'
import { Route as AppBodegaInventarioIdRouteImport } from './routes/_app.bodega.inventario.$id'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CartaIdMesaRoute = CartaIdMesaRouteImport.update({
  id: '/carta/$idMesa',
  path: '/carta/$idMesa',
  getParentRoute: () => rootRouteImport,
} as any)
const AppMenuRoute = AppMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracionRoute = AppConfiguracionRouteImport.update({
  id: '/configuracion',
  path: '/configuracion',
  getParentRoute: () => AppRoute,
} as any)
const AppBodegaRoute = AppBodegaRouteImport.update({
  id: '/bodega',
  path: '/bodega',
  getParentRoute: () => AppRoute,
} as any)
const AppMenuIndexRoute = AppMenuIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppMenuRoute,
} as any)
const AppConfiguracionIndexRoute = AppConfiguracionIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppConfiguracionRoute,
} as any)
const AppBodegaIndexRoute = AppBodegaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppBodegaRoute,
} as any)
const AppMenuRecetasRoute = AppMenuRecetasRouteImport.update({
  id: '/recetas',
  path: '/recetas',
  getParentRoute: () => AppMenuRoute,
} as any)
const AppMenuProductosRoute = AppMenuProductosRouteImport.update({
  id: '/productos',
  path: '/productos',
  getParentRoute: () => AppMenuRoute,
} as any)
const AppMenuCategoriasRoute = AppMenuCategoriasRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => AppMenuRoute,
} as any)
const AppConfiguracionUsuariosRoute =
  AppConfiguracionUsuariosRouteImport.update({
    id: '/usuarios',
    path: '/usuarios',
    getParentRoute: () => AppConfiguracionRoute,
  } as any)
const AppConfiguracionMesasRoute = AppConfiguracionMesasRouteImport.update({
  id: '/mesas',
  path: '/mesas',
  getParentRoute: () => AppConfiguracionRoute,
} as any)
const AppBodegaProveedoresInsumosRoute =
  AppBodegaProveedoresInsumosRouteImport.update({
    id: '/proveedores-insumos',
    path: '/proveedores-insumos',
    getParentRoute: () => AppBodegaRoute,
  } as any)
const AppBodegaInventarioRoute = AppBodegaInventarioRouteImport.update({
  id: '/inventario',
  path: '/inventario',
  getParentRoute: () => AppBodegaRoute,
} as any)
const AppBodegaComprasRoute = AppBodegaComprasRouteImport.update({
  id: '/compras',
  path: '/compras',
  getParentRoute: () => AppBodegaRoute,
} as any)
const AppMenuRecetasIndexRoute = AppMenuRecetasIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppMenuRecetasRoute,
} as any)
const AppBodegaInventarioIndexRoute =
  AppBodegaInventarioIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppBodegaInventarioRoute,
  } as any)
const AppMenuRecetasNuevaRoute = AppMenuRecetasNuevaRouteImport.update({
  id: '/nueva',
  path: '/nueva',
  getParentRoute: () => AppMenuRecetasRoute,
} as any)
const AppMenuRecetasIdRoute = AppMenuRecetasIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppMenuRecetasRoute,
} as any)
const AppBodegaInventarioIdRoute = AppBodegaInventarioIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppBodegaInventarioRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/bodega': typeof AppBodegaRouteWithChildren
  '/configuracion': typeof AppConfiguracionRouteWithChildren
  '/dashboard': typeof AppDashboardRoute
  '/menu': typeof AppMenuRouteWithChildren
  '/carta/$idMesa': typeof CartaIdMesaRoute
  '/bodega/compras': typeof AppBodegaComprasRoute
  '/bodega/inventario': typeof AppBodegaInventarioRouteWithChildren
  '/bodega/proveedores-insumos': typeof AppBodegaProveedoresInsumosRoute
  '/configuracion/mesas': typeof AppConfiguracionMesasRoute
  '/configuracion/usuarios': typeof AppConfiguracionUsuariosRoute
  '/menu/categorias': typeof AppMenuCategoriasRoute
  '/menu/productos': typeof AppMenuProductosRoute
  '/menu/recetas': typeof AppMenuRecetasRouteWithChildren
  '/bodega/': typeof AppBodegaIndexRoute
  '/configuracion/': typeof AppConfiguracionIndexRoute
  '/menu/': typeof AppMenuIndexRoute
  '/bodega/inventario/$id': typeof AppBodegaInventarioIdRoute
  '/menu/recetas/$id': typeof AppMenuRecetasIdRoute
  '/menu/recetas/nueva': typeof AppMenuRecetasNuevaRoute
  '/bodega/inventario/': typeof AppBodegaInventarioIndexRoute
  '/menu/recetas/': typeof AppMenuRecetasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard': typeof AppDashboardRoute
  '/carta/$idMesa': typeof CartaIdMesaRoute
  '/bodega/compras': typeof AppBodegaComprasRoute
  '/bodega/proveedores-insumos': typeof AppBodegaProveedoresInsumosRoute
  '/configuracion/mesas': typeof AppConfiguracionMesasRoute
  '/configuracion/usuarios': typeof AppConfiguracionUsuariosRoute
  '/menu/categorias': typeof AppMenuCategoriasRoute
  '/menu/productos': typeof AppMenuProductosRoute
  '/bodega': typeof AppBodegaIndexRoute
  '/configuracion': typeof AppConfiguracionIndexRoute
  '/menu': typeof AppMenuIndexRoute
  '/bodega/inventario/$id': typeof AppBodegaInventarioIdRoute
  '/menu/recetas/$id': typeof AppMenuRecetasIdRoute
  '/menu/recetas/nueva': typeof AppMenuRecetasNuevaRoute
  '/bodega/inventario': typeof AppBodegaInventarioIndexRoute
  '/menu/recetas': typeof AppMenuRecetasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_app/bodega': typeof AppBodegaRouteWithChildren
  '/_app/configuracion': typeof AppConfiguracionRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/menu': typeof AppMenuRouteWithChildren
  '/carta/$idMesa': typeof CartaIdMesaRoute
  '/_app/bodega/compras': typeof AppBodegaComprasRoute
  '/_app/bodega/inventario': typeof AppBodegaInventarioRouteWithChildren
  '/_app/bodega/proveedores-insumos': typeof AppBodegaProveedoresInsumosRoute
  '/_app/configuracion/mesas': typeof AppConfiguracionMesasRoute
  '/_app/configuracion/usuarios': typeof AppConfiguracionUsuariosRoute
  '/_app/menu/categorias': typeof AppMenuCategoriasRoute
  '/_app/menu/productos': typeof AppMenuProductosRoute
  '/_app/menu/recetas': typeof AppMenuRecetasRouteWithChildren
  '/_app/bodega/': typeof AppBodegaIndexRoute
  '/_app/configuracion/': typeof AppConfiguracionIndexRoute
  '/_app/menu/': typeof AppMenuIndexRoute
  '/_app/bodega/inventario/$id': typeof AppBodegaInventarioIdRoute
  '/_app/menu/recetas/$id': typeof AppMenuRecetasIdRoute
  '/_app/menu/recetas/nueva': typeof AppMenuRecetasNuevaRoute
  '/_app/bodega/inventario/': typeof AppBodegaInventarioIndexRoute
  '/_app/menu/recetas/': typeof AppMenuRecetasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/bodega'
    | '/configuracion'
    | '/dashboard'
    | '/menu'
    | '/carta/$idMesa'
    | '/bodega/compras'
    | '/bodega/inventario'
    | '/bodega/proveedores-insumos'
    | '/configuracion/mesas'
    | '/configuracion/usuarios'
    | '/menu/categorias'
    | '/menu/productos'
    | '/menu/recetas'
    | '/bodega/'
    | '/configuracion/'
    | '/menu/'
    | '/bodega/inventario/$id'
    | '/menu/recetas/$id'
    | '/menu/recetas/nueva'
    | '/bodega/inventario/'
    | '/menu/recetas/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/dashboard'
    | '/carta/$idMesa'
    | '/bodega/compras'
    | '/bodega/proveedores-insumos'
    | '/configuracion/mesas'
    | '/configuracion/usuarios'
    | '/menu/categorias'
    | '/menu/productos'
    | '/bodega'
    | '/configuracion'
    | '/menu'
    | '/bodega/inventario/$id'
    | '/menu/recetas/$id'
    | '/menu/recetas/nueva'
    | '/bodega/inventario'
    | '/menu/recetas'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/register'
    | '/_app/bodega'
    | '/_app/configuracion'
    | '/_app/dashboard'
    | '/_app/menu'
    | '/carta/$idMesa'
    | '/_app/bodega/compras'
    | '/_app/bodega/inventario'
    | '/_app/bodega/proveedores-insumos'
    | '/_app/configuracion/mesas'
    | '/_app/configuracion/usuarios'
    | '/_app/menu/categorias'
    | '/_app/menu/productos'
    | '/_app/menu/recetas'
    | '/_app/bodega/'
    | '/_app/configuracion/'
    | '/_app/menu/'
    | '/_app/bodega/inventario/$id'
    | '/_app/menu/recetas/$id'
    | '/_app/menu/recetas/nueva'
    | '/_app/bodega/inventario/'
    | '/_app/menu/recetas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  CartaIdMesaRoute: typeof CartaIdMesaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carta/$idMesa': {
      id: '/carta/$idMesa'
      path: '/carta/$idMesa'
      fullPath: '/carta/$idMesa'
      preLoaderRoute: typeof CartaIdMesaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/menu': {
      id: '/_app/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof AppMenuRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/configuracion': {
      id: '/_app/configuracion'
      path: '/configuracion'
      fullPath: '/configuracion'
      preLoaderRoute: typeof AppConfiguracionRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/bodega': {
      id: '/_app/bodega'
      path: '/bodega'
      fullPath: '/bodega'
      preLoaderRoute: typeof AppBodegaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/menu/': {
      id: '/_app/menu/'
      path: '/'
      fullPath: '/menu/'
      preLoaderRoute: typeof AppMenuIndexRouteImport
      parentRoute: typeof AppMenuRoute
    }
    '/_app/configuracion/': {
      id: '/_app/configuracion/'
      path: '/'
      fullPath: '/configuracion/'
      preLoaderRoute: typeof AppConfiguracionIndexRouteImport
      parentRoute: typeof AppConfiguracionRoute
    }
    '/_app/bodega/': {
      id: '/_app/bodega/'
      path: '/'
      fullPath: '/bodega/'
      preLoaderRoute: typeof AppBodegaIndexRouteImport
      parentRoute: typeof AppBodegaRoute
    }
    '/_app/menu/recetas': {
      id: '/_app/menu/recetas'
      path: '/recetas'
      fullPath: '/menu/recetas'
      preLoaderRoute: typeof AppMenuRecetasRouteImport
      parentRoute: typeof AppMenuRoute
    }
    '/_app/menu/productos': {
      id: '/_app/menu/productos'
      path: '/productos'
      fullPath: '/menu/productos'
      preLoaderRoute: typeof AppMenuProductosRouteImport
      parentRoute: typeof AppMenuRoute
    }
    '/_app/menu/categorias': {
      id: '/_app/menu/categorias'
      path: '/categorias'
      fullPath: '/menu/categorias'
      preLoaderRoute: typeof AppMenuCategoriasRouteImport
      parentRoute: typeof AppMenuRoute
    }
    '/_app/configuracion/usuarios': {
      id: '/_app/configuracion/usuarios'
      path: '/usuarios'
      fullPath: '/configuracion/usuarios'
      preLoaderRoute: typeof AppConfiguracionUsuariosRouteImport
      parentRoute: typeof AppConfiguracionRoute
    }
    '/_app/configuracion/mesas': {
      id: '/_app/configuracion/mesas'
      path: '/mesas'
      fullPath: '/configuracion/mesas'
      preLoaderRoute: typeof AppConfiguracionMesasRouteImport
      parentRoute: typeof AppConfiguracionRoute
    }
    '/_app/bodega/proveedores-insumos': {
      id: '/_app/bodega/proveedores-insumos'
      path: '/proveedores-insumos'
      fullPath: '/bodega/proveedores-insumos'
      preLoaderRoute: typeof AppBodegaProveedoresInsumosRouteImport
      parentRoute: typeof AppBodegaRoute
    }
    '/_app/bodega/inventario': {
      id: '/_app/bodega/inventario'
      path: '/inventario'
      fullPath: '/bodega/inventario'
      preLoaderRoute: typeof AppBodegaInventarioRouteImport
      parentRoute: typeof AppBodegaRoute
    }
    '/_app/bodega/compras': {
      id: '/_app/bodega/compras'
      path: '/compras'
      fullPath: '/bodega/compras'
      preLoaderRoute: typeof AppBodegaComprasRouteImport
      parentRoute: typeof AppBodegaRoute
    }
    '/_app/menu/recetas/': {
      id: '/_app/menu/recetas/'
      path: '/'
      fullPath: '/menu/recetas/'
      preLoaderRoute: typeof AppMenuRecetasIndexRouteImport
      parentRoute: typeof AppMenuRecetasRoute
    }
    '/_app/bodega/inventario/': {
      id: '/_app/bodega/inventario/'
      path: '/'
      fullPath: '/bodega/inventario/'
      preLoaderRoute: typeof AppBodegaInventarioIndexRouteImport
      parentRoute: typeof AppBodegaInventarioRoute
    }
    '/_app/menu/recetas/nueva': {
      id: '/_app/menu/recetas/nueva'
      path: '/nueva'
      fullPath: '/menu/recetas/nueva'
      preLoaderRoute: typeof AppMenuRecetasNuevaRouteImport
      parentRoute: typeof AppMenuRecetasRoute
    }
    '/_app/menu/recetas/$id': {
      id: '/_app/menu/recetas/$id'
      path: '/$id'
      fullPath: '/menu/recetas/$id'
      preLoaderRoute: typeof AppMenuRecetasIdRouteImport
      parentRoute: typeof AppMenuRecetasRoute
    }
    '/_app/bodega/inventario/$id': {
      id: '/_app/bodega/inventario/$id'
      path: '/$id'
      fullPath: '/bodega/inventario/$id'
      preLoaderRoute: typeof AppBodegaInventarioIdRouteImport
      parentRoute: typeof AppBodegaInventarioRoute
    }
  }
}

interface AppBodegaInventarioRouteChildren {
  AppBodegaInventarioIdRoute: typeof AppBodegaInventarioIdRoute
  AppBodegaInventarioIndexRoute: typeof AppBodegaInventarioIndexRoute
}

const AppBodegaInventarioRouteChildren: AppBodegaInventarioRouteChildren = {
  AppBodegaInventarioIdRoute: AppBodegaInventarioIdRoute,
  AppBodegaInventarioIndexRoute: AppBodegaInventarioIndexRoute,
}

const AppBodegaInventarioRouteWithChildren =
  AppBodegaInventarioRoute._addFileChildren(AppBodegaInventarioRouteChildren)

interface AppBodegaRouteChildren {
  AppBodegaComprasRoute: typeof AppBodegaComprasRoute
  AppBodegaInventarioRoute: typeof AppBodegaInventarioRouteWithChildren
  AppBodegaProveedoresInsumosRoute: typeof AppBodegaProveedoresInsumosRoute
  AppBodegaIndexRoute: typeof AppBodegaIndexRoute
}

const AppBodegaRouteChildren: AppBodegaRouteChildren = {
  AppBodegaComprasRoute: AppBodegaComprasRoute,
  AppBodegaInventarioRoute: AppBodegaInventarioRouteWithChildren,
  AppBodegaProveedoresInsumosRoute: AppBodegaProveedoresInsumosRoute,
  AppBodegaIndexRoute: AppBodegaIndexRoute,
}

const AppBodegaRouteWithChildren = AppBodegaRoute._addFileChildren(
  AppBodegaRouteChildren,
)

interface AppConfiguracionRouteChildren {
  AppConfiguracionMesasRoute: typeof AppConfiguracionMesasRoute
  AppConfiguracionUsuariosRoute: typeof AppConfiguracionUsuariosRoute
  AppConfiguracionIndexRoute: typeof AppConfiguracionIndexRoute
}

const AppConfiguracionRouteChildren: AppConfiguracionRouteChildren = {
  AppConfiguracionMesasRoute: AppConfiguracionMesasRoute,
  AppConfiguracionUsuariosRoute: AppConfiguracionUsuariosRoute,
  AppConfiguracionIndexRoute: AppConfiguracionIndexRoute,
}

const AppConfiguracionRouteWithChildren =
  AppConfiguracionRoute._addFileChildren(AppConfiguracionRouteChildren)

interface AppMenuRecetasRouteChildren {
  AppMenuRecetasIdRoute: typeof AppMenuRecetasIdRoute
  AppMenuRecetasNuevaRoute: typeof AppMenuRecetasNuevaRoute
  AppMenuRecetasIndexRoute: typeof AppMenuRecetasIndexRoute
}

const AppMenuRecetasRouteChildren: AppMenuRecetasRouteChildren = {
  AppMenuRecetasIdRoute: AppMenuRecetasIdRoute,
  AppMenuRecetasNuevaRoute: AppMenuRecetasNuevaRoute,
  AppMenuRecetasIndexRoute: AppMenuRecetasIndexRoute,
}

const AppMenuRecetasRouteWithChildren = AppMenuRecetasRoute._addFileChildren(
  AppMenuRecetasRouteChildren,
)

interface AppMenuRouteChildren {
  AppMenuCategoriasRoute: typeof AppMenuCategoriasRoute
  AppMenuProductosRoute: typeof AppMenuProductosRoute
  AppMenuRecetasRoute: typeof AppMenuRecetasRouteWithChildren
  AppMenuIndexRoute: typeof AppMenuIndexRoute
}

const AppMenuRouteChildren: AppMenuRouteChildren = {
  AppMenuCategoriasRoute: AppMenuCategoriasRoute,
  AppMenuProductosRoute: AppMenuProductosRoute,
  AppMenuRecetasRoute: AppMenuRecetasRouteWithChildren,
  AppMenuIndexRoute: AppMenuIndexRoute,
}

const AppMenuRouteWithChildren =
  AppMenuRoute._addFileChildren(AppMenuRouteChildren)

interface AppRouteChildren {
  AppBodegaRoute: typeof AppBodegaRouteWithChildren
  AppConfiguracionRoute: typeof AppConfiguracionRouteWithChildren
  AppDashboardRoute: typeof AppDashboardRoute
  AppMenuRoute: typeof AppMenuRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppBodegaRoute: AppBodegaRouteWithChildren,
  AppConfiguracionRoute: AppConfiguracionRouteWithChildren,
  AppDashboardRoute: AppDashboardRoute,
  AppMenuRoute: AppMenuRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  CartaIdMesaRoute: CartaIdMesaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
